services:
  note-app:
    image: chrplus6/toolsplus:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: toolsplus
    ports:
      - "80:80"
    volumes:
      - ../data:/toolsplus/data
    restart: unless-stopped
