services:
  note-app:
    image: chrplus/toolsplus:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: toolsplus
    ports:
      - "80:80"
    volumes:
      - ./data:/data
    restart: unless-stopped
